# Generated by Django 5.2 on 2025-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=500)),
                ('other_symptoms', models.TextField(blank=True, null=True)),
                ('extra_comments', models.TextField(blank=True, null=True)),
                ('medical_record', models.FileField(blank=True, null=True, upload_to='medical_records/')),
            ],
        ),
    ]
