# Generated by Django 5.2 on 2025-05-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nurseannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
