# Generated by Django 5.2 on 2025-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_healthreport_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthreport',
            old_name='other_symptoms',
            new_name='extra_comment',
        ),
        migrations.RenameField(
            model_name='healthreport',
            old_name='reviewed',
            new_name='nurse_viewed',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='extra_comments',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='healthreport',
            name='nurse_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
