# Generated by Django 3.1.12 on 2025-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_other_symptoms_healthreport_extra_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthreport',
            old_name='extra_comment',
            new_name='other_symptoms',
        ),
        migrations.RenameField(
            model_name='healthreport',
            old_name='nurse_viewed',
            new_name='reviewed',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='nurse_comment',
        ),
        migrations.AddField(
            model_name='healthreport',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='medical_record',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nurseannouncement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nursestatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
