# Generated by Django 3.1.12 on 2025-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250521_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
